# Deploy Zola site to GitHub Pages
name: Zola on GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:   # allows you to trigger manually from GitHub UI

jobs:
  build_and_deploy:
    name: Build and Deploy Site
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          submodules: recursive   # fetch theme submodule too

      - name: Build and deploy
        uses: shalzz/zola-deploy-action@v0.21.0
        env:
          PAGES_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
