# https://github.com/shalzz/zola-deploy-action
name: Zola on GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build for PR or Release Check
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4

      - name: Build only (with drafts)
        uses: shalzz/zola-deploy-action@v0.21.0
        env:
          BUILD_ONLY: true
          BUILD_FLAGS: --drafts
        # No deploy — just validate build

  build_and_deploy:
    name: Build and Deploy Site
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
      - name: Build and deploy
        uses: shalzz/zola-deploy-action@v0.21.0
        env:
          PAGES_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
